# Generated by Django 4.0.4 on 2022-06-09 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tag', models.CharField(max_length=16)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('image', models.URLField(max_length=400)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorys')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=400)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorys')),
            ],
        ),
    ]
